In [1]:
import numpy as np

data = np.random.normal(0, 1, 10)
data

array([-0.61203188, -0.59298352, -1.49926331,  0.83818198,  1.48351525,
       -0.13650845, -1.0731203 , -1.72236118, -1.10435479,  1.39419603])

In [19]:
# np.sort()는 원본을 변경하지 않음!
np.sort(data), data

(array([1, 2, 3, 4, 5, 6, 7]), array([7, 5, 3, 1, 2, 6, 4]))

In [20]:
# 최대값, 최소값의 인덱스 찾기
i1 = np.argmin(data)
i2 = np.argmax(data)

i1, i2, data[i1], data[i2]

(np.int64(3), np.int64(0), np.int64(1), np.int64(7))

In [21]:
# argsort
idx = np.argsort(data)
idx, data[idx]

(array([3, 4, 2, 6, 1, 5, 0]), array([1, 2, 3, 4, 5, 6, 7]))

In [22]:
# argsort는 데이터를 바꿀 수 없을 때, k개 찾기에서 유용
data[idx][:3]

array([1, 2, 3])

In [23]:
data = np.random.randint(0, 10, (4,6))
data, data.shape

(array([[2, 1, 6, 9, 7, 9],
        [2, 8, 8, 6, 6, 2],
        [3, 7, 5, 1, 3, 5],
        [4, 5, 4, 9, 7, 3]], dtype=int32),
 (4, 6))

In [13]:
np.sort(data)

array([[0, 0, 1, 5, 6, 8],
       [3, 5, 6, 8, 8, 8],
       [2, 2, 4, 7, 9, 9],
       [0, 1, 2, 5, 8, 9]], dtype=int32)

In [14]:
np.sort(data, axis=0)

array([[1, 0, 0, 0, 1, 2],
       [5, 2, 5, 3, 2, 5],
       [8, 8, 7, 4, 6, 6],
       [9, 9, 8, 8, 9, 8]], dtype=int32)

In [16]:
np.sort(data, axis=1)

array([[0, 0, 1, 5, 6, 8],
       [3, 5, 6, 8, 8, 8],
       [2, 2, 4, 7, 9, 9],
       [0, 1, 2, 5, 8, 9]], dtype=int32)

In [17]:
data = np.random.randint(0, 10, 7)
data

array([4, 4, 6, 6, 9, 2, 3], dtype=int32)

In [27]:
data = np.arange(1,20)
np.random.shuffle(data) # 원본 변경
data

array([10, 13,  2,  4, 18, 15, 19, 12,  7, 11, 17,  6,  9,  3,  5, 14,  8,
       16,  1])

In [28]:
np.partition(data, 3)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

# Pandas