In [2]:
import numpy as np

data = np.random.normal(0, 1, 10)
data

array([-0.94391908, -0.55244573, -0.97700164,  0.99070686, -0.15628306,
       -2.19958978,  0.9310809 ,  0.86012501, -0.96734109,  0.73309328])

In [4]:
# np.sort()는 원본을 변경하지 않음!
np.sort(data), data

(array([-2.19958978, -0.97700164, -0.96734109, -0.94391908, -0.55244573,
        -0.15628306,  0.73309328,  0.86012501,  0.9310809 ,  0.99070686]),
 array([-0.94391908, -0.55244573, -0.97700164,  0.99070686, -0.15628306,
        -2.19958978,  0.9310809 ,  0.86012501, -0.96734109,  0.73309328]))

In [6]:
np.min(data), np.max(data)

(np.float64(-2.1995897818314605), np.float64(0.9907068629847772))

In [7]:
# 최대값, 최소값의 인덱스 찾기
i1 = np.argmin(data)
i2 = np.argmax(data)

i1, i2, data[i1], data[i2]

(np.int64(5),
 np.int64(3),
 np.float64(-2.1995897818314605),
 np.float64(0.9907068629847772))

In [9]:
idx = np.argsort(data)
idx, data[idx]

(array([5, 2, 8, 0, 1, 4, 9, 7, 6, 3]),
 array([-2.19958978, -0.97700164, -0.96734109, -0.94391908, -0.55244573,
        -0.15628306,  0.73309328,  0.86012501,  0.9310809 ,  0.99070686]))

In [10]:
# argsort
# 원본 데이터를 변경하지 않을 때 또는 사본을 만들지도 않을 때 유용하게 사용할 수 있다!
idx = np.argsort(data)
idx, data[idx]

(array([5, 2, 8, 0, 1, 4, 9, 7, 6, 3]),
 array([-2.19958978, -0.97700164, -0.96734109, -0.94391908, -0.55244573,
        -0.15628306,  0.73309328,  0.86012501,  0.9310809 ,  0.99070686]))

In [11]:
# argsort는 데이터를 바꿀 수 없을 때, k개 찾기에서 유용
data[idx][:3]

array([-2.19958978, -0.97700164, -0.96734109])

In [12]:
data[[5,2,8]][:3] # 와 같은 것! fancy index

array([-2.19958978, -0.97700164, -0.96734109])

In [15]:
data = np.random.randint(0, 10, (4,6))
data, data.shape

(array([[4, 9, 5, 2, 2, 2],
        [1, 1, 2, 0, 7, 6],
        [1, 9, 6, 1, 4, 9],
        [2, 3, 4, 3, 8, 0]], dtype=int32),
 (4, 6))

In [18]:
np.sort(data)

array([[2, 2, 2, 4, 5, 9],
       [0, 1, 1, 2, 6, 7],
       [1, 1, 4, 6, 9, 9],
       [0, 2, 3, 3, 4, 8]], dtype=int32)

In [19]:
np.sort(data, axis=0)

array([[1, 1, 2, 0, 2, 0],
       [1, 3, 4, 1, 4, 2],
       [2, 9, 5, 2, 7, 6],
       [4, 9, 6, 3, 8, 9]], dtype=int32)

In [20]:
np.sort(data, axis=1)

array([[2, 2, 2, 4, 5, 9],
       [0, 1, 1, 2, 6, 7],
       [1, 1, 4, 6, 9, 9],
       [0, 2, 3, 3, 4, 8]], dtype=int32)

In [21]:
data = np.random.randint(0, 10, 7)
data

array([3, 3, 4, 2, 2, 1, 5], dtype=int32)

In [22]:
data = np.arange(1,20)
np.random.shuffle(data) # 원본 변경
data

array([13, 17,  9, 12, 16,  8,  1, 14,  5,  3, 15,  6,  7, 18,  2, 11, 19,
       10,  4])

In [23]:
np.partition(data, 3) # 이것은?

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

# Pandas